import Head from "next/head";

import styles from "./index.module.css";
import {GraphCanvas} from "reagraph";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>T3</span> App
          </h1>
          <GraphCanvas nodes={[]} edges={[]}></GraphCanvas>
        </div>
      </main>
    </>
  );
}
